
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-23T08:54:18-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b3d2a5a5aba2c93d721363bcececb218a423db5",
 "version": "v0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
