# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AssetDrumRollChild(Model):
    """AssetDrumRollChild.

    :param drum_roll_diameter:
    :type drum_roll_diameter: int
    :param drum_roll_diameter_unit:
    :type drum_roll_diameter_unit: str
    """

    _attribute_map = {
        'drum_roll_diameter': {'key': 'DrumRollDiameter', 'type': 'int'},
        'drum_roll_diameter_unit': {'key': 'DrumRollDiameterUnit', 'type': 'str'},
    }

    def __init__(self, *, drum_roll_diameter: int=None, drum_roll_diameter_unit: str=None, **kwargs) -> None:
        super(AssetDrumRollChild, self).__init__(**kwargs)
        self.drum_roll_diameter = drum_roll_diameter
        self.drum_roll_diameter_unit = drum_roll_diameter_unit
