# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SpectrumChartSettingsResponse(Model):
    """SpectrumChartSettingsResponse.

    :param frequency_domain_settings:
    :type frequency_domain_settings:
     ~smartdiagnostics_sdk.models.FrequencyDomainSettingChild
    :param time_domain_settings:
    :type time_domain_settings: ~smartdiagnostics_sdk.models.MarkerChild
    """

    _attribute_map = {
        'frequency_domain_settings': {'key': 'FrequencyDomainSettings', 'type': 'FrequencyDomainSettingChild'},
        'time_domain_settings': {'key': 'TimeDomainSettings', 'type': 'MarkerChild'},
    }

    def __init__(self, *, frequency_domain_settings=None, time_domain_settings=None, **kwargs) -> None:
        super(SpectrumChartSettingsResponse, self).__init__(**kwargs)
        self.frequency_domain_settings = frequency_domain_settings
        self.time_domain_settings = time_domain_settings
