# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SystemOverviewResponse(Model):
    """SystemOverviewResponse.

    All required parameters must be populated in order to send to Azure.

    :param is_snoozed: Required.
    :type is_snoozed: bool
    :param description:
    :type description: str
    :param is_collector_dependent_system: Required.
    :type is_collector_dependent_system: bool
    :param is_favorited: Required.
    :type is_favorited: bool
    :param is_visible: Required.
    :type is_visible: bool
    :param asset_count: Required.
    :type asset_count: int
    :param asset_status_count:
    :type asset_status_count:
     ~smartdiagnostics_sdk.models.AssetsStatusCountChild
    :param id: Required.
    :type id: str
    :param name: Required.
    :type name: str
    :param abbreviation:
    :type abbreviation: str
    :param active: Required.
    :type active: bool
    :param is_paused: Required.
    :type is_paused: bool
    :param created: Required.
    :type created: datetime
    :param corporation: Required.
    :type corporation: ~smartdiagnostics_sdk.models.CorporationChild
    :param location: Required.
    :type location: ~smartdiagnostics_sdk.models.LocationChild
    """

    _validation = {
        'is_snoozed': {'required': True},
        'is_collector_dependent_system': {'required': True},
        'is_favorited': {'required': True},
        'is_visible': {'required': True},
        'asset_count': {'required': True},
        'id': {'required': True},
        'name': {'required': True},
        'active': {'required': True},
        'is_paused': {'required': True},
        'created': {'required': True},
        'corporation': {'required': True},
        'location': {'required': True},
    }

    _attribute_map = {
        'is_snoozed': {'key': 'IsSnoozed', 'type': 'bool'},
        'description': {'key': 'Description', 'type': 'str'},
        'is_collector_dependent_system': {'key': 'IsCollectorDependentSystem', 'type': 'bool'},
        'is_favorited': {'key': 'IsFavorited', 'type': 'bool'},
        'is_visible': {'key': 'IsVisible', 'type': 'bool'},
        'asset_count': {'key': 'AssetCount', 'type': 'int'},
        'asset_status_count': {'key': 'AssetStatusCount', 'type': 'AssetsStatusCountChild'},
        'id': {'key': 'Id', 'type': 'str'},
        'name': {'key': 'Name', 'type': 'str'},
        'abbreviation': {'key': 'Abbreviation', 'type': 'str'},
        'active': {'key': 'Active', 'type': 'bool'},
        'is_paused': {'key': 'IsPaused', 'type': 'bool'},
        'created': {'key': 'Created', 'type': 'iso-8601'},
        'corporation': {'key': 'Corporation', 'type': 'CorporationChild'},
        'location': {'key': 'Location', 'type': 'LocationChild'},
    }

    def __init__(self, **kwargs):
        super(SystemOverviewResponse, self).__init__(**kwargs)
        self.is_snoozed = kwargs.get('is_snoozed', None)
        self.description = kwargs.get('description', None)
        self.is_collector_dependent_system = kwargs.get('is_collector_dependent_system', None)
        self.is_favorited = kwargs.get('is_favorited', None)
        self.is_visible = kwargs.get('is_visible', None)
        self.asset_count = kwargs.get('asset_count', None)
        self.asset_status_count = kwargs.get('asset_status_count', None)
        self.id = kwargs.get('id', None)
        self.name = kwargs.get('name', None)
        self.abbreviation = kwargs.get('abbreviation', None)
        self.active = kwargs.get('active', None)
        self.is_paused = kwargs.get('is_paused', None)
        self.created = kwargs.get('created', None)
        self.corporation = kwargs.get('corporation', None)
        self.location = kwargs.get('location', None)
