# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 16:52
from __future__ import unicode_literals

from django.db import migrations, models


from cmsplugin_zinnia.choices_helpers import (get_template_choices,
                                              get_default_template)


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_zinnia', '0002_fix_djangocms330_incompatible_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestentriesplugin',
            name='template_to_render',
            field=models.CharField(blank=False, choices=get_template_choices(), default=get_default_template(), help_text='template used to display the plugin', max_length=250, verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='queryentriesplugin',
            name='template_to_render',
            field=models.CharField(blank=False, choices=get_template_choices(), default=get_default_template(), help_text='template used to display the plugin', max_length=250, verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='randomentriesplugin',
            name='template_to_render',
            field=models.CharField(blank=False, choices=get_template_choices(), default=get_default_template(), help_text='template used to display the plugin', max_length=250, verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='selectedentriesplugin',
            name='template_to_render',
            field=models.CharField(blank=False, choices=get_template_choices(), default=get_default_template(), help_text='template used to display the plugin', max_length=250, verbose_name='template'),
        ),
    ]
