from enum import Enum
from typing import Any, Optional

class Sensor(Enum):
    res_1080: Any = ...
    res_4k: Any = ...
    res_12_mp: Any = ...

class VideoMode(Enum):
    preview: int = ...
    video: int = ...

class Oak:
    DEVICES_IN_USE: Any = ...
    device_info: Any = ...
    model_config: Any = ...
    usb2: Any = ...
    sensor: Any = ...
    camera_pipeline: Any = ...
    color_stream_node: Any = ...
    neural_network_node: Any = ...
    device: Any = ...
    def __init__(self, model_id: Any, sensor: Any = ..., video_mode: Any = ..., usb2: bool = ..., device_info: Optional[Any] = ...) -> None: ...
    @classmethod
    def get_devices_in_use(cls): ...
    @staticmethod
    def get_available_devices(): ...
    def read(self): ...
    def get_model_result(self, **inference_args: Any): ...
    def get_model_data(self): ...
    frame_output_queue: Any = ...
    nn_output_queue: Any = ...
    controller_queue: Any = ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: Any, value: Any, traceback: Any) -> None: ...
