from edgeiq import bounding_box as bounding_box
from typing import Any, Optional

class CorrelationTracker:
    def __init__(self, max_objects: Optional[Any] = ...) -> None: ...
    def start(self, image: Any, prediction: Any) -> None: ...
    @property
    def count(self): ...
    def update(self, image: Any): ...
    def stop_all(self) -> None: ...

class CentroidTracker:
    def __init__(self, deregister_frames: int = ..., max_distance: int = ...) -> None: ...
    def update(self, predictions: Any): ...
