from typing import Any

DESCRIPTOR: Any
GOPROTO_ENUM_PREFIX_FIELD_NUMBER: int
goproto_enum_prefix: Any
GOPROTO_ENUM_STRINGER_FIELD_NUMBER: int
goproto_enum_stringer: Any
ENUM_STRINGER_FIELD_NUMBER: int
enum_stringer: Any
ENUM_CUSTOMNAME_FIELD_NUMBER: int
enum_customname: Any
ENUMDECL_FIELD_NUMBER: int
enumdecl: Any
ENUMVALUE_CUSTOMNAME_FIELD_NUMBER: int
enumvalue_customname: Any
GOPROTO_GETTERS_ALL_FIELD_NUMBER: int
goproto_getters_all: Any
GOPROTO_ENUM_PREFIX_ALL_FIELD_NUMBER: int
goproto_enum_prefix_all: Any
GOPROTO_STRINGER_ALL_FIELD_NUMBER: int
goproto_stringer_all: Any
VERBOSE_EQUAL_ALL_FIELD_NUMBER: int
verbose_equal_all: Any
FACE_ALL_FIELD_NUMBER: int
face_all: Any
GOSTRING_ALL_FIELD_NUMBER: int
gostring_all: Any
POPULATE_ALL_FIELD_NUMBER: int
populate_all: Any
STRINGER_ALL_FIELD_NUMBER: int
stringer_all: Any
ONLYONE_ALL_FIELD_NUMBER: int
onlyone_all: Any
EQUAL_ALL_FIELD_NUMBER: int
equal_all: Any
DESCRIPTION_ALL_FIELD_NUMBER: int
description_all: Any
TESTGEN_ALL_FIELD_NUMBER: int
testgen_all: Any
BENCHGEN_ALL_FIELD_NUMBER: int
benchgen_all: Any
MARSHALER_ALL_FIELD_NUMBER: int
marshaler_all: Any
UNMARSHALER_ALL_FIELD_NUMBER: int
unmarshaler_all: Any
STABLE_MARSHALER_ALL_FIELD_NUMBER: int
stable_marshaler_all: Any
SIZER_ALL_FIELD_NUMBER: int
sizer_all: Any
GOPROTO_ENUM_STRINGER_ALL_FIELD_NUMBER: int
goproto_enum_stringer_all: Any
ENUM_STRINGER_ALL_FIELD_NUMBER: int
enum_stringer_all: Any
UNSAFE_MARSHALER_ALL_FIELD_NUMBER: int
unsafe_marshaler_all: Any
UNSAFE_UNMARSHALER_ALL_FIELD_NUMBER: int
unsafe_unmarshaler_all: Any
GOPROTO_EXTENSIONS_MAP_ALL_FIELD_NUMBER: int
goproto_extensions_map_all: Any
GOPROTO_UNRECOGNIZED_ALL_FIELD_NUMBER: int
goproto_unrecognized_all: Any
GOGOPROTO_IMPORT_FIELD_NUMBER: int
gogoproto_import: Any
PROTOSIZER_ALL_FIELD_NUMBER: int
protosizer_all: Any
COMPARE_ALL_FIELD_NUMBER: int
compare_all: Any
TYPEDECL_ALL_FIELD_NUMBER: int
typedecl_all: Any
ENUMDECL_ALL_FIELD_NUMBER: int
enumdecl_all: Any
GOPROTO_REGISTRATION_FIELD_NUMBER: int
goproto_registration: Any
GOPROTO_GETTERS_FIELD_NUMBER: int
goproto_getters: Any
GOPROTO_STRINGER_FIELD_NUMBER: int
goproto_stringer: Any
VERBOSE_EQUAL_FIELD_NUMBER: int
verbose_equal: Any
FACE_FIELD_NUMBER: int
face: Any
GOSTRING_FIELD_NUMBER: int
gostring: Any
POPULATE_FIELD_NUMBER: int
populate: Any
STRINGER_FIELD_NUMBER: int
stringer: Any
ONLYONE_FIELD_NUMBER: int
onlyone: Any
EQUAL_FIELD_NUMBER: int
equal: Any
DESCRIPTION_FIELD_NUMBER: int
description: Any
TESTGEN_FIELD_NUMBER: int
testgen: Any
BENCHGEN_FIELD_NUMBER: int
benchgen: Any
MARSHALER_FIELD_NUMBER: int
marshaler: Any
UNMARSHALER_FIELD_NUMBER: int
unmarshaler: Any
STABLE_MARSHALER_FIELD_NUMBER: int
stable_marshaler: Any
SIZER_FIELD_NUMBER: int
sizer: Any
UNSAFE_MARSHALER_FIELD_NUMBER: int
unsafe_marshaler: Any
UNSAFE_UNMARSHALER_FIELD_NUMBER: int
unsafe_unmarshaler: Any
GOPROTO_EXTENSIONS_MAP_FIELD_NUMBER: int
goproto_extensions_map: Any
GOPROTO_UNRECOGNIZED_FIELD_NUMBER: int
goproto_unrecognized: Any
PROTOSIZER_FIELD_NUMBER: int
protosizer: Any
COMPARE_FIELD_NUMBER: int
compare: Any
TYPEDECL_FIELD_NUMBER: int
typedecl: Any
NULLABLE_FIELD_NUMBER: int
nullable: Any
EMBED_FIELD_NUMBER: int
embed: Any
CUSTOMTYPE_FIELD_NUMBER: int
customtype: Any
CUSTOMNAME_FIELD_NUMBER: int
customname: Any
JSONTAG_FIELD_NUMBER: int
jsontag: Any
MORETAGS_FIELD_NUMBER: int
moretags: Any
CASTTYPE_FIELD_NUMBER: int
casttype: Any
CASTKEY_FIELD_NUMBER: int
castkey: Any
CASTVALUE_FIELD_NUMBER: int
castvalue: Any
STDTIME_FIELD_NUMBER: int
stdtime: Any
STDDURATION_FIELD_NUMBER: int
stdduration: Any
