
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-23T07:37:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5648fc0cf02b72a789189efa700436613b3e912",
 "version": "0.6.2.post.dev222"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
