
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-02T11:11:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "23f6dbcb97723db4d81cb7a3fc1c16c2ace93bbc",
 "version": "v1.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
