# coding: utf-8

"""
    IncQuery Server Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.18.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from iqs_client.configuration import Configuration


class ModelonImpactWorkspaceDescriptor(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'workspace_id': 'str',
        'compartment_uri': 'str'
    }

    attribute_map = {
        'name': 'name',
        'workspace_id': 'workspaceId',
        'compartment_uri': 'compartmentURI'
    }

    def __init__(self, name=None, workspace_id=None, compartment_uri=None, local_vars_configuration=None):  # noqa: E501
        """ModelonImpactWorkspaceDescriptor - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._workspace_id = None
        self._compartment_uri = None
        self.discriminator = None

        self.name = name
        self.workspace_id = workspace_id
        self.compartment_uri = compartment_uri

    @property
    def name(self):
        """Gets the name of this ModelonImpactWorkspaceDescriptor.  # noqa: E501


        :return: The name of this ModelonImpactWorkspaceDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ModelonImpactWorkspaceDescriptor.


        :param name: The name of this ModelonImpactWorkspaceDescriptor.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def workspace_id(self):
        """Gets the workspace_id of this ModelonImpactWorkspaceDescriptor.  # noqa: E501


        :return: The workspace_id of this ModelonImpactWorkspaceDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._workspace_id

    @workspace_id.setter
    def workspace_id(self, workspace_id):
        """Sets the workspace_id of this ModelonImpactWorkspaceDescriptor.


        :param workspace_id: The workspace_id of this ModelonImpactWorkspaceDescriptor.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and workspace_id is None:  # noqa: E501
            raise ValueError("Invalid value for `workspace_id`, must not be `None`")  # noqa: E501

        self._workspace_id = workspace_id

    @property
    def compartment_uri(self):
        """Gets the compartment_uri of this ModelonImpactWorkspaceDescriptor.  # noqa: E501


        :return: The compartment_uri of this ModelonImpactWorkspaceDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._compartment_uri

    @compartment_uri.setter
    def compartment_uri(self, compartment_uri):
        """Sets the compartment_uri of this ModelonImpactWorkspaceDescriptor.


        :param compartment_uri: The compartment_uri of this ModelonImpactWorkspaceDescriptor.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and compartment_uri is None:  # noqa: E501
            raise ValueError("Invalid value for `compartment_uri`, must not be `None`")  # noqa: E501

        self._compartment_uri = compartment_uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelonImpactWorkspaceDescriptor):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ModelonImpactWorkspaceDescriptor):
            return True

        return self.to_dict() != other.to_dict()
