'''__init__.py'''


from mastapy._internal.dummy_base_class_importer import _DummyBaseClassImport


with _DummyBaseClassImport():
    from ._927 import AddendumModificationDistributionRule
    from ._928 import BacklashSpecification
    from ._929 import BasicRackProfiles
    from ._930 import CaseHardeningProperties
    from ._931 import CreateNewSuitableCutterOption
    from ._932 import CrossedAxisCylindricalGearPair
    from ._933 import CrossedAxisCylindricalGearPairLineContact
    from ._934 import CrossedAxisCylindricalGearPairPointContact
    from ._935 import CylindricalGearAbstractRack
    from ._936 import CylindricalGearAbstractRackFlank
    from ._937 import CylindricalGearBasicRack
    from ._938 import CylindricalGearBasicRackFlank
    from ._939 import CylindricalGearCuttingOptions
    from ._940 import CylindricalGearDefaults
    from ._941 import CylindricalGearDesign
    from ._942 import CylindricalGearDesignConstraint
    from ._943 import CylindricalGearDesignConstraints
    from ._944 import CylindricalGearDesignConstraintsDatabase
    from ._945 import CylindricalGearDesignConstraintSettings
    from ._946 import CylindricalGearDesignSettings
    from ._947 import CylindricalGearFlankDesign
    from ._948 import CylindricalGearMeshDesign
    from ._949 import CylindricalGearMeshFlankDesign
    from ._950 import CylindricalGearPinionTypeCutter
    from ._951 import CylindricalGearPinionTypeCutterFlank
    from ._952 import CylindricalGearProfileMeasurement
    from ._953 import CylindricalGearProfileMeasurementType
    from ._954 import CylindricalGearProfileModifications
    from ._955 import CylindricalGearSetDesign
    from ._956 import CylindricalGearSetFlankDesign
    from ._957 import CylindricalGearSetMacroGeometryOptimiser
    from ._958 import CylindricalGearSetManufacturingConfigurationSelection
    from ._959 import CylindricalGearTableMGItemDetail
    from ._960 import CylindricalGearTableWithMGCharts
    from ._961 import CylindricalGearToothThicknessSpecification
    from ._962 import CylindricalMeshAngularBacklash
    from ._963 import CylindricalMeshedGear
    from ._964 import CylindricalMeshedGearFlank
    from ._965 import CylindricalMeshLinearBacklashSpecification
    from ._966 import CylindricalPlanetaryGearSetDesign
    from ._967 import CylindricalPlanetGearDesign
    from ._968 import DIN3967AllowanceSeries
    from ._969 import DIN3967ToleranceSeries
    from ._970 import FinishStockSpecification
    from ._971 import FinishToothThicknessDesignSpecification
    from ._972 import GearFitSystems
    from ._973 import GearManufacturingConfigSetupViewModel
    from ._974 import GearSetFCAImportSetup
    from ._975 import GearSetManufacturingConfigurationSetup
    from ._976 import GeometrySpecificationType
    from ._977 import HardenedMaterialProperties
    from ._978 import HardnessProfileCalculationMethod
    from ._979 import HeatTreatmentType
    from ._980 import ISO6336Geometry
    from ._981 import ISO6336GeometryBase
    from ._982 import ISO6336GeometryForShapedGears
    from ._983 import ISO6336GeometryManufactured
    from ._984 import LinearBacklashSepcification
    from ._985 import LTCALoadCaseModifiableSettings
    from ._986 import LtcaSettings
    from ._987 import MicroGeometryConvention
    from ._988 import MicroGeometryProfileConvention
    from ._989 import Micropitting
    from ._990 import NamedPlanetAssemblyIndex
    from ._991 import NamedPlanetSideBandAmplitudeFactor
    from ._992 import ReadonlyToothThicknessSpecification
    from ._993 import RelativeMeasurementViewModel
    from ._994 import RelativeValuesSpecification
    from ._995 import Scuffing
    from ._996 import ScuffingCoefficientOfFrictionMethods
    from ._997 import ScuffingTemperatureMethodsAGMA
    from ._998 import ScuffingTemperatureMethodsISO
    from ._999 import ShaperEdgeTypes
    from ._1000 import SpurGearLoadSharingCodes
    from ._1001 import StandardRack
    from ._1002 import StandardRackFlank
    from ._1003 import SurfaceRoughness
    from ._1004 import ThicknessType
    from ._1005 import TiffAnalysisSettings
    from ._1006 import TipAlterationCoefficientMethod
    from ._1007 import TolerancedMetalMeasurements
    from ._1008 import TolerancedValueSpecification
    from ._1009 import ToothThicknessSpecification
    from ._1010 import ToothThicknessSpecificationBase
    from ._1011 import TypeOfMechanismHousing
    from ._1012 import Usage
