# coding: utf-8

"""
    IncQuery Server Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.18.0rc1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from iqs_client.configuration import Configuration


class AttributeStoreEntry(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'attribute': 'EAttributeDescriptor',
        'tuples': 'list[AttributeSlot]'
    }

    attribute_map = {
        'attribute': 'attribute',
        'tuples': 'tuples'
    }

    def __init__(self, attribute=None, tuples=None, local_vars_configuration=None):  # noqa: E501
        """AttributeStoreEntry - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._attribute = None
        self._tuples = None
        self.discriminator = None

        self.attribute = attribute
        self.tuples = tuples

    @property
    def attribute(self):
        """Gets the attribute of this AttributeStoreEntry.  # noqa: E501


        :return: The attribute of this AttributeStoreEntry.  # noqa: E501
        :rtype: EAttributeDescriptor
        """
        return self._attribute

    @attribute.setter
    def attribute(self, attribute):
        """Sets the attribute of this AttributeStoreEntry.


        :param attribute: The attribute of this AttributeStoreEntry.  # noqa: E501
        :type: EAttributeDescriptor
        """
        if self.local_vars_configuration.client_side_validation and attribute is None:  # noqa: E501
            raise ValueError("Invalid value for `attribute`, must not be `None`")  # noqa: E501

        self._attribute = attribute

    @property
    def tuples(self):
        """Gets the tuples of this AttributeStoreEntry.  # noqa: E501


        :return: The tuples of this AttributeStoreEntry.  # noqa: E501
        :rtype: list[AttributeSlot]
        """
        return self._tuples

    @tuples.setter
    def tuples(self, tuples):
        """Sets the tuples of this AttributeStoreEntry.


        :param tuples: The tuples of this AttributeStoreEntry.  # noqa: E501
        :type: list[AttributeSlot]
        """
        if self.local_vars_configuration.client_side_validation and tuples is None:  # noqa: E501
            raise ValueError("Invalid value for `tuples`, must not be `None`")  # noqa: E501

        self._tuples = tuples

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AttributeStoreEntry):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AttributeStoreEntry):
            return True

        return self.to_dict() != other.to_dict()
