# coding: utf-8

"""
    Nucleus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NumberBucketTransform(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'buckets': 'NumberBucketFilter',
        'default_value': 'float',
        'output_column': 'str'
    }

    attribute_map = {
        'buckets': 'buckets',
        'default_value': 'default_value',
        'output_column': 'output_column'
    }

    def __init__(self, buckets=None, default_value=None, output_column=None):  # noqa: E501
        """NumberBucketTransform - a model defined in OpenAPI"""  # noqa: E501

        self._buckets = None
        self._default_value = None
        self._output_column = None
        self.discriminator = None

        if buckets is not None:
            self.buckets = buckets
        if default_value is not None:
            self.default_value = default_value
        self.output_column = output_column

    @property
    def buckets(self):
        """Gets the buckets of this NumberBucketTransform.  # noqa: E501


        :return: The buckets of this NumberBucketTransform.  # noqa: E501
        :rtype: NumberBucketFilter
        """
        return self._buckets

    @buckets.setter
    def buckets(self, buckets):
        """Sets the buckets of this NumberBucketTransform.


        :param buckets: The buckets of this NumberBucketTransform.  # noqa: E501
        :type: NumberBucketFilter
        """

        self._buckets = buckets

    @property
    def default_value(self):
        """Gets the default_value of this NumberBucketTransform.  # noqa: E501


        :return: The default_value of this NumberBucketTransform.  # noqa: E501
        :rtype: float
        """
        return self._default_value

    @default_value.setter
    def default_value(self, default_value):
        """Sets the default_value of this NumberBucketTransform.


        :param default_value: The default_value of this NumberBucketTransform.  # noqa: E501
        :type: float
        """

        self._default_value = default_value

    @property
    def output_column(self):
        """Gets the output_column of this NumberBucketTransform.  # noqa: E501


        :return: The output_column of this NumberBucketTransform.  # noqa: E501
        :rtype: str
        """
        return self._output_column

    @output_column.setter
    def output_column(self, output_column):
        """Sets the output_column of this NumberBucketTransform.


        :param output_column: The output_column of this NumberBucketTransform.  # noqa: E501
        :type: str
        """
        if output_column is None:
            raise ValueError("Invalid value for `output_column`, must not be `None`")  # noqa: E501

        self._output_column = output_column

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NumberBucketTransform):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
