# coding: utf-8

"""
    Nucleus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ProlearnCredit(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'credit_type': 'ProlearnCreditType',
        'credit_value': 'int'
    }

    attribute_map = {
        'credit_type': 'CreditType',
        'credit_value': 'CreditValue'
    }

    def __init__(self, credit_type=None, credit_value=None):  # noqa: E501
        """ProlearnCredit - a model defined in OpenAPI"""  # noqa: E501

        self._credit_type = None
        self._credit_value = None
        self.discriminator = None

        self.credit_type = credit_type
        self.credit_value = credit_value

    @property
    def credit_type(self):
        """Gets the credit_type of this ProlearnCredit.  # noqa: E501


        :return: The credit_type of this ProlearnCredit.  # noqa: E501
        :rtype: ProlearnCreditType
        """
        return self._credit_type

    @credit_type.setter
    def credit_type(self, credit_type):
        """Sets the credit_type of this ProlearnCredit.


        :param credit_type: The credit_type of this ProlearnCredit.  # noqa: E501
        :type: ProlearnCreditType
        """
        if credit_type is None:
            raise ValueError("Invalid value for `credit_type`, must not be `None`")  # noqa: E501

        self._credit_type = credit_type

    @property
    def credit_value(self):
        """Gets the credit_value of this ProlearnCredit.  # noqa: E501


        :return: The credit_value of this ProlearnCredit.  # noqa: E501
        :rtype: int
        """
        return self._credit_value

    @credit_value.setter
    def credit_value(self, credit_value):
        """Sets the credit_value of this ProlearnCredit.


        :param credit_value: The credit_value of this ProlearnCredit.  # noqa: E501
        :type: int
        """
        if credit_value is None:
            raise ValueError("Invalid value for `credit_value`, must not be `None`")  # noqa: E501

        self._credit_value = credit_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProlearnCredit):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
