"""
    MMS Reference Implementation API

    Documentation for MMS API  # noqa: E501

    The version of the OpenAPI document: 4.0.3
    Contact: mms@openmbee.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mms_python_client
from mms_python_client.model.rejection import Rejection


class TestRejection(unittest.TestCase):
    """Rejection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRejection(self):
        """Test Rejection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Rejection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
