"""
    MMS Reference Implementation API

    Documentation for MMS API  # noqa: E501

    The version of the OpenAPI document: 4.0.3
    Contact: mms@openmbee.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mms_python_client
from mms_python_client.model.element_version import ElementVersion
globals()['ElementVersion'] = ElementVersion
from mms_python_client.model.commit import Commit


class TestCommit(unittest.TestCase):
    """Commit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommit(self):
        """Test Commit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Commit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
