"""
    MMS Reference Implementation API

    Documentation for MMS API  # noqa: E501

    The version of the OpenAPI document: 4.0.3
    Contact: mms@openmbee.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mms_python_client
from mms_python_client.model.jwt_authentication_request import JwtAuthenticationRequest


class TestJwtAuthenticationRequest(unittest.TestCase):
    """JwtAuthenticationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJwtAuthenticationRequest(self):
        """Test JwtAuthenticationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JwtAuthenticationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
