
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-23T05:16:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "776cecc3b565c4ea9c6b9ed2029bce9660dd6816",
 "version": "0.6.2.post.dev218"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
