# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_sizecostaccounting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrylineaccount',
            options={'default_permissions': [], 'ordering': ['entry__date_value', 'entry__id', 'account__code', 'third'], 'verbose_name': 'entry line of account', 'verbose_name_plural': 'entry lines of account'},
        ),
        migrations.AddField(
            model_name='entrylineaccount',
            name='costaccounting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.CostAccounting', verbose_name='cost accounting'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.FiscalYear', verbose_name='fiscal year'),
        ),
    ]
