# coding: utf-8

"""
    XTRF Home Portal API

    XTRF Home Portal API enables you to perform operations on Projects, Quotes, Customers, Vendors etc. as a XTRF Home Portal user. <br>The documentation is generated from OpenAPI specification 3.0 available <a href=\"/home-api/openapi.json\">here</a> <br>   The API client/consumer code may be easily generated in 60+ programming languages using an open source code generator available at the time of writing this documentation at <a href='https://editor.swagger.io/'>https://editor.swagger.io/</a> Thank you for using XTRF Application Programming interface (XTRF API). By using the API you agree to the terms below. If you disagree with any of these terms, XTRF does not grant you a license to use the XTRF API. XTRF reserves the right to update and change these terms from time to time without a prior notice of API users. You can always find the most recent version of these terms here:   # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xtrf_api
from xtrf_api.api.dictionaries_api import DictionariesApi  # noqa: E501
from xtrf_api.rest import ApiException


class TestDictionariesApi(unittest.TestCase):
    """DictionariesApi unit test stubs"""

    def setUp(self):
        self.api = DictionariesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_active(self):
        """Test case for get_active

        Returns active dictionary entities for all types.  # noqa: E501
        """
        pass

    def test_get_active_by_type(self):
        """Test case for get_active_by_type

        Returns active values from a given dictionary.  # noqa: E501
        """
        pass

    def test_get_all1(self):
        """Test case for get_all1

        Returns dictionary entities for all types. Both active and not active ones.  # noqa: E501
        """
        pass

    def test_get_all3(self):
        """Test case for get_all3

        Returns services list  # noqa: E501
        """
        pass

    def test_get_all_active(self):
        """Test case for get_all_active

        Returns active services list  # noqa: E501
        """
        pass

    def test_get_all_by_type(self):
        """Test case for get_all_by_type

        Returns all values (both active and not active) from a given dictionary.  # noqa: E501
        """
        pass

    def test_get_by_type_and_id(self):
        """Test case for get_by_type_and_id

        Returns specific value from a given dictionary.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
