
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-03-01T17:14:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e46a581c1ae2babb8e95a4721b06df6c900961b2",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
