
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-26T17:16:54+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "498e88a36476bbf5896778668b072be2dbc7c85b",
 "version": "2.0.55.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
