from edc_auth.codenames import screening

screening += [
    "mocca_screening.add_carestatus",
    "mocca_screening.add_dailyclosinglog",
    "mocca_screening.add_moccaregistercontact",
    "mocca_screening.add_subjectrefusal",
    "mocca_screening.add_subjectrefusalscreening",
    "mocca_screening.add_subjectscreening",
    "mocca_screening.change_carestatus",
    "mocca_screening.change_dailyclosinglog",
    "mocca_screening.change_moccaregister",
    "mocca_screening.change_moccaregistercontact",
    "mocca_screening.change_subjectrefusal",
    "mocca_screening.change_subjectrefusalscreening",
    "mocca_screening.change_subjectscreening",
    "mocca_screening.delete_carestatus",
    "mocca_screening.delete_dailyclosinglog",
    "mocca_screening.delete_moccaregistercontact",
    "mocca_screening.delete_subjectrefusal",
    "mocca_screening.delete_subjectrefusalscreening",
    "mocca_screening.delete_subjectscreening",
    "mocca_screening.view_carestatus",
    "mocca_screening.view_dailyclosinglog",
    "mocca_screening.view_moccaregister",
    "mocca_screening.view_moccaregistercontact",
    "mocca_screening.view_historicalcarestatus",
    "mocca_screening.view_historicaldailyclosinglog",
    "mocca_screening.view_historicalmoccaregister",
    "mocca_screening.view_historicalmoccaregistercontact",
    "mocca_screening.view_historicalsubjectrefusal",
    "mocca_screening.view_historicalsubjectrefusalscreening",
    "mocca_screening.view_historicalsubjectscreening",
    "mocca_screening.view_subjectrefusal",
    "mocca_screening.view_subjectrefusalscreening",
    "mocca_screening.view_subjectscreening",
]
