# coding: utf-8

"""
    IncQuery Server Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.18.0rc1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import iqs_client
from iqs_client.models.mms_repository_info_response import MMSRepositoryInfoResponse  # noqa: E501
from iqs_client.rest import ApiException

class TestMMSRepositoryInfoResponse(unittest.TestCase):
    """MMSRepositoryInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MMSRepositoryInfoResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = iqs_client.models.mms_repository_info_response.MMSRepositoryInfoResponse()  # noqa: E501
        if include_optional :
            return MMSRepositoryInfoResponse(
                repository_structure = iqs_client.models.mms_repository_structure.MMSRepositoryStructure(
                    id = '0', 
                    title = '0', 
                    orgs = [
                        iqs_client.models.mms_organization.MMSOrganization(
                            org_id = '6384a103-766c-46e0-830d-8a3b1f479479', 
                            name = 'IQL', 
                            projects = [
                                iqs_client.models.mms_project.MMSProject(
                                    project_id = 'PROJECT-bef4f459-5d90-41fb-bc86-4f6d4ebd2dfd', 
                                    name = 'ICS-ALLQueries', 
                                    refs = [
                                        iqs_client.models.mms_ref.MMSRef(
                                            ref_id = 'master', 
                                            name = 'master', 
                                            commits = {"commitId":"560d3959-3912-434a-a914-8d039d3c9a06"}, )
                                        ], )
                                ], )
                        ], ), 
                last_updated = '2018-10-10T12:00:00.000Z'
            )
        else :
            return MMSRepositoryInfoResponse(
                repository_structure = iqs_client.models.mms_repository_structure.MMSRepositoryStructure(
                    id = '0', 
                    title = '0', 
                    orgs = [
                        iqs_client.models.mms_organization.MMSOrganization(
                            org_id = '6384a103-766c-46e0-830d-8a3b1f479479', 
                            name = 'IQL', 
                            projects = [
                                iqs_client.models.mms_project.MMSProject(
                                    project_id = 'PROJECT-bef4f459-5d90-41fb-bc86-4f6d4ebd2dfd', 
                                    name = 'ICS-ALLQueries', 
                                    refs = [
                                        iqs_client.models.mms_ref.MMSRef(
                                            ref_id = 'master', 
                                            name = 'master', 
                                            commits = {"commitId":"560d3959-3912-434a-a914-8d039d3c9a06"}, )
                                        ], )
                                ], )
                        ], ),
                last_updated = '2018-10-10T12:00:00.000Z',
        )

    def testMMSRepositoryInfoResponse(self):
        """Test MMSRepositoryInfoResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
