
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-23T06:24:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f8e84599562b65cfd1206e145143af8b2377f2b4",
 "version": "0.6.2.post.dev220"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
