# coding: utf-8

"""
    Nucleus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import nucleus_client
from nucleus_client.models.client_package import ClientPackage  # noqa: E501
from nucleus_client.rest import ApiException


class TestClientPackage(unittest.TestCase):
    """ClientPackage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientPackage(self):
        """Test ClientPackage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nucleus_client.models.client_package.ClientPackage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
