# coding: utf-8

"""
    Nucleus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import nucleus_client
from nucleus_client.api.default_api import DefaultApi  # noqa: E501
from nucleus_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = nucleus_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_client(self):
        """Test case for activate_client

        Reactivates a client by client code  # noqa: E501
        """
        pass

    def test_activate_user(self):
        """Test case for activate_user

        Activates a user  # noqa: E501
        """
        pass

    def test_add_api_key(self):
        """Test case for add_api_key

        Add an API user  # noqa: E501
        """
        pass

    def test_add_block_type(self):
        """Test case for add_block_type

        Add a new block type  # noqa: E501
        """
        pass

    def test_add_client(self):
        """Test case for add_client

        Add new client  # noqa: E501
        """
        pass

    def test_add_dataset(self):
        """Test case for add_dataset

        Add a new dataset  # noqa: E501
        """
        pass

    def test_add_dataset_metadata(self):
        """Test case for add_dataset_metadata

        Retrieves meta information about data stored in Druid  # noqa: E501
        """
        pass

    def test_add_download_request(self):
        """Test case for add_download_request

        Adds a new (pending) download request  # noqa: E501
        """
        pass

    def test_add_download_request_0(self):
        """Test case for add_download_request_0

        Adds a new (pending) download request  # noqa: E501
        """
        pass

    def test_add_entity_batch(self):
        """Test case for add_entity_batch

        Adds a new entity batch, and queues a task to process it  # noqa: E501
        """
        pass

    def test_add_full_page(self):
        """Test case for add_full_page

        Creates a page without removing blocks, widgets, or block_order attributes  # noqa: E501
        """
        pass

    def test_add_geodata(self):
        """Test case for add_geodata

        Adds a new geo mapping  # noqa: E501
        """
        pass

    def test_add_goal(self):
        """Test case for add_goal

        Adds a new goal  # noqa: E501
        """
        pass

    def test_add_higher_logic_activity(self):
        """Test case for add_higher_logic_activity

        Higher Logic callback  # noqa: E501
        """
        pass

    def test_add_integration(self):
        """Test case for add_integration

        Adds a new integration  # noqa: E501
        """
        pass

    def test_add_integration_sync_request(self):
        """Test case for add_integration_sync_request

        Run a sync integration      Responses:          204: The sync request was successfully queued  # noqa: E501
        """
        pass

    def test_add_integration_type(self):
        """Test case for add_integration_type

        Add a new integration type  # noqa: E501
        """
        pass

    def test_add_page(self):
        """Test case for add_page

        Creates a page from a page template  # noqa: E501
        """
        pass

    def test_add_page_publication(self):
        """Test case for add_page_publication

        Updates page with publication information      Responses:          201: Page was updated with publication information  # noqa: E501
        """
        pass

    def test_add_page_template(self):
        """Test case for add_page_template

        Add a new page template  # noqa: E501
        """
        pass

    def test_add_partner_batch(self):
        """Test case for add_partner_batch

        Adds a new partner batch, and queues a task to process it  # noqa: E501
        """
        pass

    def test_add_password_reset_request(self):
        """Test case for add_password_reset_request

        Creates a new request to reset a user's password  # noqa: E501
        """
        pass

    def test_add_prolearn_activity(self):
        """Test case for add_prolearn_activity

        Prolearn callback  # noqa: E501
        """
        pass

    def test_add_report(self):
        """Test case for add_report

        Add a new report  # noqa: E501
        """
        pass

    def test_add_report_config(self):
        """Test case for add_report_config

        Add a new report_config  # noqa: E501
        """
        pass

    def test_add_role(self):
        """Test case for add_role

        Adds a new role  # noqa: E501
        """
        pass

    def test_add_role_permission(self):
        """Test case for add_role_permission

        Adds a new permission to a role  # noqa: E501
        """
        pass

    def test_add_term(self):
        """Test case for add_term

        Adds a new term  # noqa: E501
        """
        pass

    def test_add_upload_request(self):
        """Test case for add_upload_request

        Adds a new (pending) upload request  # noqa: E501
        """
        pass

    def test_add_user(self):
        """Test case for add_user

        Adds a new user  # noqa: E501
        """
        pass

    def test_add_user_0(self):
        """Test case for add_user_0

        Notifies administrator that user has been added or deleted  # noqa: E501
        """
        pass

    def test_add_user_1(self):
        """Test case for add_user_1

        Adds a new user token  # noqa: E501
        """
        pass

    def test_add_user_role(self):
        """Test case for add_user_role

        Add a user to a role  # noqa: E501
        """
        pass

    def test_add_view(self):
        """Test case for add_view

        Adds a new view  # noqa: E501
        """
        pass

    def test_add_widget_type(self):
        """Test case for add_widget_type

        Adds a new widget type  # noqa: E501
        """
        pass

    def test_change_password(self):
        """Test case for change_password

        Changes a users password  # noqa: E501
        """
        pass

    def test_cleanup_dataset_segments(self):
        """Test case for cleanup_dataset_segments

        Cleanup old segments for a dataset  # noqa: E501
        """
        pass

    def test_create_client_package(self):
        """Test case for create_client_package

        Creates a new client package  # noqa: E501
        """
        pass

    def test_delete_activity_by_key(self):
        """Test case for delete_activity_by_key

        Hard delete an activity by external key  # noqa: E501
        """
        pass

    def test_delete_api_key(self):
        """Test case for delete_api_key

        Deletes an API user by ID  # noqa: E501
        """
        pass

    def test_delete_block_type(self):
        """Test case for delete_block_type

        Deletes a block type by ID  # noqa: E501
        """
        pass

    def test_delete_client(self):
        """Test case for delete_client

        Deletes a client by ID  # noqa: E501
        """
        pass

    def test_delete_dataset(self):
        """Test case for delete_dataset

        Deletes a dataset by ID  # noqa: E501
        """
        pass

    def test_delete_goal(self):
        """Test case for delete_goal

        Deletes a goal by id  # noqa: E501
        """
        pass

    def test_delete_integration(self):
        """Test case for delete_integration

        Deletes an integration by ID  # noqa: E501
        """
        pass

    def test_delete_page(self):
        """Test case for delete_page

        Deletes a page by ID  # noqa: E501
        """
        pass

    def test_delete_page_preference(self):
        """Test case for delete_page_preference

        Deletes page preferences for the authenticated user  # noqa: E501
        """
        pass

    def test_delete_page_publication(self):
        """Test case for delete_page_publication

        Deletes publication information for a page      Responses:          204: Page publication information was successfully deleted  # noqa: E501
        """
        pass

    def test_delete_page_template(self):
        """Test case for delete_page_template

        Deletes a page template by ID  # noqa: E501
        """
        pass

    def test_delete_page_template_by_slug(self):
        """Test case for delete_page_template_by_slug

        Deletes all page templates with the specified slug  # noqa: E501
        """
        pass

    def test_delete_report(self):
        """Test case for delete_report

        Deletes a report by ID  # noqa: E501
        """
        pass

    def test_delete_report_config(self):
        """Test case for delete_report_config

        Deletes a report_config by ID  # noqa: E501
        """
        pass

    def test_delete_role(self):
        """Test case for delete_role

        Deletes a role by ID  # noqa: E501
        """
        pass

    def test_delete_role_permission(self):
        """Test case for delete_role_permission

        Deletes a permission for a specific role by ID  # noqa: E501
        """
        pass

    def test_delete_schema(self):
        """Test case for delete_schema

        Deletes the schema associated with an activity      Responses:          204: Schema was successfully deleted  # noqa: E501
        """
        pass

    def test_delete_term(self):
        """Test case for delete_term

        Deletes a term by ID  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Deletes an active user by ID  # noqa: E501
        """
        pass

    def test_delete_user_0(self):
        """Test case for delete_user_0

        Deletes an active user token by ID  # noqa: E501
        """
        pass

    def test_delete_user_role(self):
        """Test case for delete_user_role

        Deletes a user from a role by user ID  # noqa: E501
        """
        pass

    def test_delete_widget_type(self):
        """Test case for delete_widget_type

        Deletes an existing widget type  # noqa: E501
        """
        pass

    def test_get_api_key(self):
        """Test case for get_api_key

        Get an API user by ID  # noqa: E501
        """
        pass

    def test_get_block_type(self):
        """Test case for get_block_type

        Get a block type by ID  # noqa: E501
        """
        pass

    def test_get_block_type_by_name(self):
        """Test case for get_block_type_by_name

        Get a block type by name  # noqa: E501
        """
        pass

    def test_get_client(self):
        """Test case for get_client

        Get client by ID  # noqa: E501
        """
        pass

    def test_get_client_by_code(self):
        """Test case for get_client_by_code

        Gets a client by client code  # noqa: E501
        """
        pass

    def test_get_dataset(self):
        """Test case for get_dataset

        Get a dataset by ID  # noqa: E501
        """
        pass

    def test_get_dataset_by_name(self):
        """Test case for get_dataset_by_name

        Get a dataset by name  # noqa: E501
        """
        pass

    def test_get_dataset_by_slug(self):
        """Test case for get_dataset_by_slug

        Get a dataset by slug  # noqa: E501
        """
        pass

    def test_get_download(self):
        """Test case for get_download

        Gets data for a completed download  # noqa: E501
        """
        pass

    def test_get_download_request(self):
        """Test case for get_download_request

        Gets a download request by id  # noqa: E501
        """
        pass

    def test_get_entity_batch(self):
        """Test case for get_entity_batch

        Gets an entity batch by id  # noqa: E501
        """
        pass

    def test_get_entity_batch_health(self):
        """Test case for get_entity_batch_health

        Gets a health summary of processed entity batches  # noqa: E501
        """
        pass

    def test_get_filter_values(self):
        """Test case for get_filter_values

        Retrieves a list of possible values for a given set of dimensions  # noqa: E501
        """
        pass

    def test_get_goal_by_goal(self):
        """Test case for get_goal_by_goal

        Gets a goal by id  # noqa: E501
        """
        pass

    def test_get_integration(self):
        """Test case for get_integration

        Gets an integration by ID  # noqa: E501
        """
        pass

    def test_get_integration_type(self):
        """Test case for get_integration_type

        Get integration type by id  # noqa: E501
        """
        pass

    def test_get_integration_type_by_name(self):
        """Test case for get_integration_type_by_name

        Get integration type by name  # noqa: E501
        """
        pass

    def test_get_jobs_overview(self):
        """Test case for get_jobs_overview

        Gets an overview of data processing jobs  # noqa: E501
        """
        pass

    def test_get_page(self):
        """Test case for get_page

        Gets a page by ID  # noqa: E501
        """
        pass

    def test_get_page_by_slug(self):
        """Test case for get_page_by_slug

        Gets a page by slug  # noqa: E501
        """
        pass

    def test_get_page_preference(self):
        """Test case for get_page_preference

        Gets page preferences for the authenticated user  # noqa: E501
        """
        pass

    def test_get_page_template(self):
        """Test case for get_page_template

        Gets a page template by ID  # noqa: E501
        """
        pass

    def test_get_page_template_by_slug(self):
        """Test case for get_page_template_by_slug

        Gets a page template by slug  # noqa: E501
        """
        pass

    def test_get_password_reset_by_key(self):
        """Test case for get_password_reset_by_key

        Gets a user by the reset key associated with them  # noqa: E501
        """
        pass

    def test_get_report(self):
        """Test case for get_report

        Get a report by ID  # noqa: E501
        """
        pass

    def test_get_report_config(self):
        """Test case for get_report_config

        Get a report_config by ID  # noqa: E501
        """
        pass

    def test_get_report_config_by_name(self):
        """Test case for get_report_config_by_name

        Get a report_config by name  # noqa: E501
        """
        pass

    def test_get_role(self):
        """Test case for get_role

        Gets a role by ID  # noqa: E501
        """
        pass

    def test_get_role_by_name(self):
        """Test case for get_role_by_name

        Gets a role by name  # noqa: E501
        """
        pass

    def test_get_role_by_slug(self):
        """Test case for get_role_by_slug

        Gets a role slug  # noqa: E501
        """
        pass

    def test_get_role_permission(self):
        """Test case for get_role_permission

        Gets a permission for a specific role by ID  # noqa: E501
        """
        pass

    def test_get_schema(self):
        """Test case for get_schema

        Get a schema by ID  # noqa: E501
        """
        pass

    def test_get_term_by_term(self):
        """Test case for get_term_by_term

        Gets a term by term  # noqa: E501
        """
        pass

    def test_get_upload_request(self):
        """Test case for get_upload_request

        Gets an upload request by id  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Gets a user by ID  # noqa: E501
        """
        pass

    def test_get_user_activation_by_key(self):
        """Test case for get_user_activation_by_key

        Gets the user associated with an activation key  # noqa: E501
        """
        pass

    def test_get_user_by_email(self):
        """Test case for get_user_by_email

        Gets a user by email address  # noqa: E501
        """
        pass

    def test_get_user_by_idtoken(self):
        """Test case for get_user_by_idtoken

        List active tokens associated with a user  # noqa: E501
        """
        pass

    def test_get_view(self):
        """Test case for get_view

        Get a view by ID  # noqa: E501
        """
        pass

    def test_get_view_by_keys(self):
        """Test case for get_view_by_keys

        Get a list of views by hash key  # noqa: E501
        """
        pass

    def test_get_widget_type(self):
        """Test case for get_widget_type

        Get widget type by ID  # noqa: E501
        """
        pass

    def test_get_widget_type_by_name(self):
        """Test case for get_widget_type_by_name

        Get widget type by name  # noqa: E501
        """
        pass

    def test_list_activities(self):
        """Test case for list_activities

        Get activities from a dataset in JSON or CSV  # noqa: E501
        """
        pass

    def test_list_api_keys(self):
        """Test case for list_api_keys

        List all API users associated with a client  # noqa: E501
        """
        pass

    def test_list_block_types(self):
        """Test case for list_block_types

        List all block types  # noqa: E501
        """
        pass

    def test_list_client_packages(self):
        """Test case for list_client_packages

        List available client packages  # noqa: E501
        """
        pass

    def test_list_client_settings(self):
        """Test case for list_client_settings

        List all client-specific settings  # noqa: E501
        """
        pass

    def test_list_clients(self):
        """Test case for list_clients

        List all clients  # noqa: E501
        """
        pass

    def test_list_completed_jobs(self):
        """Test case for list_completed_jobs

        Gets a list of completed data processing jobs  # noqa: E501
        """
        pass

    def test_list_datasets(self):
        """Test case for list_datasets

        List all datasets associated with a client  # noqa: E501
        """
        pass

    def test_list_download_requests(self):
        """Test case for list_download_requests

        Gets all unexpired download requests for the authenticated user  # noqa: E501
        """
        pass

    def test_list_entity_batches(self):
        """Test case for list_entity_batches

        List all entity batches associated with a client  # noqa: E501
        """
        pass

    def test_list_geodata(self):
        """Test case for list_geodata

        List all geodata  # noqa: E501
        """
        pass

    def test_list_goals(self):
        """Test case for list_goals

        List all goals associated with a client  # noqa: E501
        """
        pass

    def test_list_incomplete_jobs(self):
        """Test case for list_incomplete_jobs

        Gets a list of incomplete data processing jobs  # noqa: E501
        """
        pass

    def test_list_integration_types(self):
        """Test case for list_integration_types

        List all integration types  # noqa: E501
        """
        pass

    def test_list_integrations(self):
        """Test case for list_integrations

        List all integrations associated with a client  # noqa: E501
        """
        pass

    def test_list_maintenance(self):
        """Test case for list_maintenance

        Cleanup for a dataset      Responses:          202: Delete task was successfully queued  # noqa: E501
        """
        pass

    def test_list_page_preferences(self):
        """Test case for list_page_preferences

        List all page preferences associated with a client for the authenticated user  # noqa: E501
        """
        pass

    def test_list_page_templates(self):
        """Test case for list_page_templates

        List all page templates  # noqa: E501
        """
        pass

    def test_list_pages(self):
        """Test case for list_pages

        List all pages associated with a client  # noqa: E501
        """
        pass

    def test_list_pages_by_page_template(self):
        """Test case for list_pages_by_page_template

        List all pages associated with a particular page template and optionally client  # noqa: E501
        """
        pass

    def test_list_report_configs(self):
        """Test case for list_report_configs

        List all report_configs associated with a client  # noqa: E501
        """
        pass

    def test_list_reports(self):
        """Test case for list_reports

        List all reports associated with a client  # noqa: E501
        """
        pass

    def test_list_role_permissions(self):
        """Test case for list_role_permissions

        List all permissions for a specific role  # noqa: E501
        """
        pass

    def test_list_roles(self):
        """Test case for list_roles

        List roles associated with a client  # noqa: E501
        """
        pass

    def test_list_schemas(self):
        """Test case for list_schemas

        List all schemas associated with a client  # noqa: E501
        """
        pass

    def test_list_terms(self):
        """Test case for list_terms

        List all terms associated with a client  # noqa: E501
        """
        pass

    def test_list_upload_requests(self):
        """Test case for list_upload_requests

        Gets all unexpired upload requests for the authenticated user  # noqa: E501
        """
        pass

    def test_list_user_roles(self):
        """Test case for list_user_roles

        List all roles for a specific user  # noqa: E501
        """
        pass

    def test_list_users(self):
        """Test case for list_users

        List active users associated with a client  # noqa: E501
        """
        pass

    def test_list_views(self):
        """Test case for list_views

        List metadata for all views associated with a client  # noqa: E501
        """
        pass

    def test_list_widget_types(self):
        """Test case for list_widget_types

        List all widget types  # noqa: E501
        """
        pass

    def test_load_client_package(self):
        """Test case for load_client_package

        Imports data for a client into the current environment  # noqa: E501
        """
        pass

    def test_me(self):
        """Test case for me

        Get data about the authenticated user  # noqa: E501
        """
        pass

    def test_query(self):
        """Test case for query

        Performs a query against an existing dataset  # noqa: E501
        """
        pass

    def test_replace_full_page(self):
        """Test case for replace_full_page

        Replaces an existing page by ID  # noqa: E501
        """
        pass

    def test_replace_page(self):
        """Test case for replace_page

        Replaces an existing page by ID  # noqa: E501
        """
        pass

    def test_replace_templated_page(self):
        """Test case for replace_templated_page

        Replaces from a page template an existing page by ID  # noqa: E501
        """
        pass

    def test_reset_password(self):
        """Test case for reset_password

        Resets a user's password to the specified password  # noqa: E501
        """
        pass

    def test_update_api_key(self):
        """Test case for update_api_key

        Updates an existing API user  # noqa: E501
        """
        pass

    def test_update_block_type(self):
        """Test case for update_block_type

        Updates an existing block type  # noqa: E501
        """
        pass

    def test_update_client(self):
        """Test case for update_client

        Updates an existing client  # noqa: E501
        """
        pass

    def test_update_client_setting(self):
        """Test case for update_client_setting

        Insert or update new client-specific settings  # noqa: E501
        """
        pass

    def test_update_dataset(self):
        """Test case for update_dataset

        Updates an existing dataset  # noqa: E501
        """
        pass

    def test_update_geodata(self):
        """Test case for update_geodata

        Updates an existing geo type  # noqa: E501
        """
        pass

    def test_update_goal(self):
        """Test case for update_goal

        Updates an existing goal  # noqa: E501
        """
        pass

    def test_update_integration(self):
        """Test case for update_integration

        Updates an existing integration  # noqa: E501
        """
        pass

    def test_update_integration_type(self):
        """Test case for update_integration_type

        Updates an existing integration type  # noqa: E501
        """
        pass

    def test_update_page_preference(self):
        """Test case for update_page_preference

        Add or update a page preference  # noqa: E501
        """
        pass

    def test_update_report(self):
        """Test case for update_report

        Updates an existing report  # noqa: E501
        """
        pass

    def test_update_report_config(self):
        """Test case for update_report_config

        Updates an existing report_config  # noqa: E501
        """
        pass

    def test_update_role(self):
        """Test case for update_role

        Updates an existing role  # noqa: E501
        """
        pass

    def test_update_term(self):
        """Test case for update_term

        Updates an existing term  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Updates an existing user  # noqa: E501
        """
        pass

    def test_update_widget_type(self):
        """Test case for update_widget_type

        Updates an existing widget type  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
