# coding: utf-8

"""
    Nucleus API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import nucleus_client
from nucleus_client.models.cumulative_metric_order_by import CumulativeMetricOrderBy  # noqa: E501
from nucleus_client.rest import ApiException


class TestCumulativeMetricOrderBy(unittest.TestCase):
    """CumulativeMetricOrderBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCumulativeMetricOrderBy(self):
        """Test CumulativeMetricOrderBy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nucleus_client.models.cumulative_metric_order_by.CumulativeMetricOrderBy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
