# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-30 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_account', '0007_auto_20200130_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldpuser',
            name='default_redirect_uri',
            field=models.CharField(blank=True, help_text='A URL to redirect to (home page) when none other is provided in a request, e.g. on forgot password. This will be automatically updated on login', max_length=5000, null=True),
        ),
    ]
