# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-10 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_account', '0013_auto_20200505_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_backlink',
            field=models.BooleanField(default=False, help_text='(DEPRECIATED) set automatically to indicate the Model is a backlink'),
        ),
        migrations.AlterField(
            model_name='chatprofile',
            name='is_backlink',
            field=models.BooleanField(default=False, help_text='(DEPRECIATED) set automatically to indicate the Model is a backlink'),
        ),
        migrations.AlterField(
            model_name='ldpuser',
            name='is_backlink',
            field=models.BooleanField(default=False, help_text='(DEPRECIATED) set automatically to indicate the Model is a backlink'),
        ),
        migrations.AlterField(
            model_name='opclient',
            name='is_backlink',
            field=models.BooleanField(default=False, help_text='(DEPRECIATED) set automatically to indicate the Model is a backlink'),
        ),
    ]
