
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-26T19:09:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7efd0725218bf060a1a6705b5258e05dfd3b7a90",
 "version": "v1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
