# Generated by Django 2.2.2 on 2019-07-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("edc_reference", "0007_auto_20190706_0706")]

    operations = [
        migrations.AlterModelOptions(
            name="reference",
            options={
                "ordering": (
                    "identifier",
                    "report_datetime",
                    "visit_schedule_name",
                    "schedule_name",
                    "timepoint",
                    "model",
                    "field_name",
                )
            },
        ),
        migrations.RemoveIndex(model_name="reference", name="edc_referen_identif_02257f_idx"),
        migrations.RemoveIndex(model_name="reference", name="edc_referen_identif_378284_idx"),
        migrations.AlterField(
            model_name="reference",
            name="visit_code",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="reference",
            unique_together={
                (
                    "identifier",
                    "visit_schedule_name",
                    "schedule_name",
                    "visit_code",
                    "visit_code_sequence",
                    "timepoint",
                    "report_datetime",
                    "model",
                    "field_name",
                )
            },
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(
                fields=[
                    "identifier",
                    "visit_schedule_name",
                    "schedule_name",
                    "visit_code",
                    "timepoint",
                    "model",
                    "field_name",
                ],
                name="edc_referen_identif_5273cc_idx",
            ),
        ),
    ]
