# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-02-15 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_event_plot_id_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='plot_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Plot Id'),
        ),
    ]
