
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <..\src\include\frc2\command\PrintCommand.h>

#include <frc2/command/Command.h>
#include <frc2/command/Subsystem.h>




#include <rpygen/frc2__InstantCommand.hpp>

namespace rpygen {

using namespace frc2;


template <typename PyTrampolineBase, typename CxxBase = PyTrampolineBase>
using PyBasefrc2__PrintCommand = 
    Pyfrc2__InstantCommand<
        PyTrampolineBase
    
    , CxxBase
    >
;

template <typename PyTrampolineBase, typename CxxBase = PyTrampolineBase>
struct Pyfrc2__PrintCommand : PyBasefrc2__PrintCommand<PyTrampolineBase, CxxBase> {
    using PyBasefrc2__PrintCommand<PyTrampolineBase, CxxBase>::PyBasefrc2__PrintCommand;



#ifndef RPYGEN_DISABLE_KRunsWhenDisabled_v
    bool RunsWhenDisabled() const override {
PYBIND11_OVERRIDE_NAME(PYBIND11_TYPE(bool), CxxBase, "runsWhenDisabled", RunsWhenDisabled,);    }
#endif




};

}; // namespace rpygen
