# coding: utf-8

"""
    IncQuery Server Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.18.0rc1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from iqs_client.configuration import Configuration


class FeatureDescriptorProxy(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'feature_name': 'str',
        'feature_kind': 'str',
        'classifier_proxy': 'EClassifierDescriptor'
    }

    attribute_map = {
        'feature_name': 'featureName',
        'feature_kind': 'featureKind',
        'classifier_proxy': 'classifierProxy'
    }

    def __init__(self, feature_name=None, feature_kind=None, classifier_proxy=None, local_vars_configuration=None):  # noqa: E501
        """FeatureDescriptorProxy - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._feature_name = None
        self._feature_kind = None
        self._classifier_proxy = None
        self.discriminator = None

        if feature_name is not None:
            self.feature_name = feature_name
        if feature_kind is not None:
            self.feature_kind = feature_kind
        if classifier_proxy is not None:
            self.classifier_proxy = classifier_proxy

    @property
    def feature_name(self):
        """Gets the feature_name of this FeatureDescriptorProxy.  # noqa: E501


        :return: The feature_name of this FeatureDescriptorProxy.  # noqa: E501
        :rtype: str
        """
        return self._feature_name

    @feature_name.setter
    def feature_name(self, feature_name):
        """Sets the feature_name of this FeatureDescriptorProxy.


        :param feature_name: The feature_name of this FeatureDescriptorProxy.  # noqa: E501
        :type: str
        """

        self._feature_name = feature_name

    @property
    def feature_kind(self):
        """Gets the feature_kind of this FeatureDescriptorProxy.  # noqa: E501


        :return: The feature_kind of this FeatureDescriptorProxy.  # noqa: E501
        :rtype: str
        """
        return self._feature_kind

    @feature_kind.setter
    def feature_kind(self, feature_kind):
        """Sets the feature_kind of this FeatureDescriptorProxy.


        :param feature_kind: The feature_kind of this FeatureDescriptorProxy.  # noqa: E501
        :type: str
        """
        allowed_values = ["EATTRIBUTE", "EREFERENCE"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and feature_kind not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `feature_kind` ({0}), must be one of {1}"  # noqa: E501
                .format(feature_kind, allowed_values)
            )

        self._feature_kind = feature_kind

    @property
    def classifier_proxy(self):
        """Gets the classifier_proxy of this FeatureDescriptorProxy.  # noqa: E501


        :return: The classifier_proxy of this FeatureDescriptorProxy.  # noqa: E501
        :rtype: EClassifierDescriptor
        """
        return self._classifier_proxy

    @classifier_proxy.setter
    def classifier_proxy(self, classifier_proxy):
        """Sets the classifier_proxy of this FeatureDescriptorProxy.


        :param classifier_proxy: The classifier_proxy of this FeatureDescriptorProxy.  # noqa: E501
        :type: EClassifierDescriptor
        """

        self._classifier_proxy = classifier_proxy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FeatureDescriptorProxy):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FeatureDescriptorProxy):
            return True

        return self.to_dict() != other.to_dict()
