from typing import Any

DESCRIPTOR: Any
ExecType: Any
OrderStatus: Any
OrderRejectReason: Any
OrderSide: Any
OrderType: Any
OrderDuration: Any
OrderQualifier: Any
OrderStyle: Any
OrderBusiness: Any
PositionSide: Any
PositionEffect: Any
CashPositionChangeReason: Any
AlgoOrderStatus: Any
PositionSrc: Any
ExecType_Unknown: int
ExecType_New: int
ExecType_DoneForDay: int
ExecType_Canceled: int
ExecType_PendingCancel: int
ExecType_Stopped: int
ExecType_Rejected: int
ExecType_Suspended: int
ExecType_PendingNew: int
ExecType_Calculated: int
ExecType_Expired: int
ExecType_Restated: int
ExecType_PendingReplace: int
ExecType_Trade: int
ExecType_TradeCorrect: int
ExecType_TradeCancel: int
ExecType_OrderStatus: int
ExecType_CancelRejected: int
OrderStatus_Unknown: int
OrderStatus_New: int
OrderStatus_PartiallyFilled: int
OrderStatus_Filled: int
OrderStatus_DoneForDay: int
OrderStatus_Canceled: int
OrderStatus_PendingCancel: int
OrderStatus_Stopped: int
OrderStatus_Rejected: int
OrderStatus_Suspended: int
OrderStatus_PendingNew: int
OrderStatus_Calculated: int
OrderStatus_Expired: int
OrderStatus_AcceptedForBidding: int
OrderStatus_PendingReplace: int
OrderRejectReason_Unknown: int
OrderRejectReason_RiskRuleCheckFailed: int
OrderRejectReason_NoEnoughCash: int
OrderRejectReason_NoEnoughPosition: int
OrderRejectReason_IllegalAccountId: int
OrderRejectReason_IllegalStrategyId: int
OrderRejectReason_IllegalSymbol: int
OrderRejectReason_IllegalVolume: int
OrderRejectReason_IllegalPrice: int
OrderRejectReason_AccountDisabled: int
OrderRejectReason_AccountDisconnected: int
OrderRejectReason_AccountLoggedout: int
OrderRejectReason_NotInTradingSession: int
OrderRejectReason_OrderTypeNotSupported: int
OrderRejectReason_OrderStyleNotSupported: int
OrderRejectReason_Throttle: int
OrderRejectReason_SymbolSusppended: int
OrderRejectReason_Internal: int
CancelOrderRejectReason_OrderFinalized: int
CancelOrderRejectReason_UnknownOrder: int
CancelOrderRejectReason_BrokerOption: int
CancelOrderRejectReason_AlreadyInPendingCancel: int
OrderSide_Unknown: int
OrderSide_Buy: int
OrderSide_Sell: int
OrderType_Unknown: int
OrderType_Limit: int
OrderType_Limit_FAK: int
OrderType_Limit_FOK: int
OrderType_Market: int
OrderType_Market_BOC: int
OrderType_Market_BOP: int
OrderType_Market_FAK: int
OrderType_Market_FOK: int
OrderType_Market_B5TC: int
OrderType_Market_B5TL: int
OrderType_Stop: int
OrderType_AHT: int
OrderDuration_Unknown: int
OrderDuration_FAK: int
OrderDuration_FOK: int
OrderDuration_GFD: int
OrderDuration_GFS: int
OrderDuration_GTD: int
OrderDuration_GTC: int
OrderDuration_GFA: int
OrderDuration_AHT: int
OrderQualifier_Unknown: int
OrderQualifier_BOC: int
OrderQualifier_BOP: int
OrderQualifier_B5TC: int
OrderQualifier_B5TL: int
OrderStyle_Unknown: int
OrderStyle_Volume: int
OrderStyle_Value: int
OrderStyle_Percent: int
OrderStyle_TargetVolume: int
OrderStyle_TargetValue: int
OrderStyle_TargetPercent: int
OrderBusiness_NORMAL: int
OrderBusiness_STOCK_BUY: int
OrderBusiness_STOCK_SELL: int
OrderBusiness_FUTURE_BUY_OPEN: int
OrderBusiness_FUTURE_SELL_CLOSE: int
OrderBusiness_FUTURE_SELL_CLOSE_TODAY: int
OrderBusiness_FUTURE_SELL_CLOSE_YESTERDAY: int
OrderBusiness_FUTURE_SELL_OPEN: int
OrderBusiness_FUTURE_BUY_CLOSE: int
OrderBusiness_FUTURE_BUY_CLOSE_TODAY: int
OrderBusiness_FUTURE_BUY_CLOSE_YESTERDAY: int
OrderBusiness_IPO_BUY: int
OrderBusiness_CREDIT_BOM: int
OrderBusiness_CREDIT_SS: int
OrderBusiness_CREDIT_RSBBS: int
OrderBusiness_CREDIT_RCBSS: int
OrderBusiness_CREDIT_DRS: int
OrderBusiness_CREDIT_DRC: int
OrderBusiness_CREDIT_CPOM: int
OrderBusiness_CREDIT_CPOSS: int
OrderBusiness_CREDIT_BOC: int
OrderBusiness_CREDIT_SOC: int
OrderBusiness_CREDIT_CI: int
OrderBusiness_CREDIT_CO: int
OrderBusiness_CREDIT_BOM_VIP: int
OrderBusiness_CREDIT_SS_VIP: int
OrderBusiness_CREDIT_RSBBS_VIP: int
OrderBusiness_CREDIT_RCBSS_VIP: int
OrderBusiness_CREDIT_DRS_VIP: int
OrderBusiness_CREDIT_DRC_VIP: int
OrderBusiness_ETF_BUY: int
OrderBusiness_ETF_RED: int
OrderBusiness_FUND_SUB: int
OrderBusiness_FUND_BUY: int
OrderBusiness_FUND_RED: int
OrderBusiness_FUND_CONVERT: int
OrderBusiness_FUND_SPLIT: int
OrderBusiness_FUND_MERGE: int
OrderBusiness_BOND_RRP: int
OrderBusiness_BOND_CONVERTIBLE_BUY: int
OrderBusiness_BOND_CONVERTIBLE_CALL: int
OrderBusiness_BOND_CONVERTIBLE_PUT: int
OrderBusiness_BOND_CONVERTIBLE_PUT_CANCEL: int
PositionSide_Unknown: int
PositionSide_Long: int
PositionSide_Short: int
PositionEffect_Unknown: int
PositionEffect_Open: int
PositionEffect_Close: int
PositionEffect_CloseToday: int
PositionEffect_CloseYesterday: int
CashPositionChangeReason_Unknown: int
CashPositionChangeReason_Trade: int
CashPositionChangeReason_Inout: int
CashPositionChangeReason_Dividend: int
CashPositionChangeReason_Delivery: int
AlgoOrderStatus_Unknown: int
AlgoOrderStatus_Resume: int
AlgoOrderStatus_Pause: int
AlgoOrderStatus_PauseAndCancelSubOrders: int
PositionSrc_Unknown: int
PositionSrc_L1: int
PositionSrc_L2: int
AlgoOrder: Any
AlgoOrders: Any
Order: Any
Orders: Any
ExecRpt: Any
ExecRpts: Any
Cash: Any
Cashes: Any
Position: Any
Positions: Any
Account: Any
AccountInfo: Any
Accounts: Any
AccountStatus: Any
AccountStatuses: Any
AccountChannel: Any
AccountChannels: Any
AccountConnection: Any
AccountConnections: Any
