# Generated by Django 3.0.8 on 2020-07-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_journal_is_default'),
        ('payoff', '0007_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_journal',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='bank_journal', to='accounting.Journal', verbose_name='bank journal'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='temporary_account_code',
            field=models.CharField(max_length=50, default='', verbose_name='temporary account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='temporary_journal',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_journal', to='accounting.Journal', verbose_name='temporary journal'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_code',
            field=models.CharField(max_length=50, verbose_name='bank account'),
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['order_key'], 'verbose_name': 'bank code', 'verbose_name_plural': 'bank codes'},
        ),
    ]
