# Generated by Django 3.1.1 on 2020-09-22 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import nobinobi_child.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nobinobi_staff', '0008_add_partial_disability'),
        ('nobinobi_child', '0001_initial_squashed_0017_add_usage_homeopathy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='good_development',
            field=models.BooleanField(null=True, verbose_name='Good development'),
        ),
        migrations.AlterField(
            model_name='child',
            name='healthy_child',
            field=models.BooleanField(null=True, verbose_name='Healthy child'),
        ),
        migrations.AlterField(
            model_name='child',
            name='pediatrician_contact',
            field=models.BooleanField(blank=True, null=True, verbose_name='Pediatrician contact'),
        ),
        migrations.AlterField(
            model_name='child',
            name='usage_homeopathy',
            field=models.BooleanField(null=True, verbose_name='Usage homeopathy'),
        ),
        migrations.AlterField(
            model_name='child',
            name='usage_paracetamol',
            field=models.BooleanField(null=True, verbose_name='Usage paracetamol'),
        ),
        migrations.AlterField(
            model_name='child',
            name='vaccination',
            field=models.BooleanField(null=True, verbose_name='Vaccination'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='authorized_pick_up_child',
            field=models.BooleanField(null=True, verbose_name='Contact authorized to pick up the child.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='to_contact_if_needed',
            field=models.BooleanField(null=True, verbose_name='To contact if needed'),
        ),
    ]
