#  Copyright (C) 2020 <Florian Alu - Prolibre - https://prolibre.com
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 2.2 on 2019-11-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0011_auto_20191120_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='good_development',
            field=models.NullBooleanField(verbose_name='Good development'),
        ),
        migrations.AddField(
            model_name='child',
            name='health_insurance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Health Insurance'),
        ),
        migrations.AddField(
            model_name='child',
            name='healthy_child',
            field=models.NullBooleanField(verbose_name='Healthy child'),
        ),
        migrations.AddField(
            model_name='child',
            name='specific_problem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specific problem'),
        ),
        migrations.AddField(
            model_name='child',
            name='usage_paracetamol',
            field=models.NullBooleanField(verbose_name='Usage paracetamol'),
        ),
        migrations.AddField(
            model_name='child',
            name='vaccination',
            field=models.NullBooleanField(verbose_name='Vaccination'),
        ),
    ]
