
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-23T08:52:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8540e04bd86c60f5353b503db861cecd25eaebd0",
 "version": "0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
