"""
    Katalon TestOps API reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import testops_api
from testops_api.model.test_case_resource import TestCaseResource
globals()['TestCaseResource'] = TestCaseResource
from testops_api.model.external_issue_resource import ExternalIssueResource


class TestExternalIssueResource(unittest.TestCase):
    """ExternalIssueResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalIssueResource(self):
        """Test ExternalIssueResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExternalIssueResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
