"""
    Katalon TestOps API reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import testops_api
from testops_api.api.job_api import JobApi  # noqa: E501


class TestJobApi(unittest.TestCase):
    """JobApi unit test stubs"""

    def setUp(self):
        self.api = JobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel(self):
        """Test case for cancel

        Cancels a Job.  # noqa: E501
        """
        pass

    def test_get16(self):
        """Test case for get16

        Returns a Job detail.  # noqa: E501
        """
        pass

    def test_get_job(self):
        """Test case for get_job

        Returns the next queued Job of an Agent.  # noqa: E501
        """
        pass

    def test_get_latest_jobs(self):
        """Test case for get_latest_jobs

        """
        pass

    def test_get_log(self):
        """Test case for get_log

        Returns a Job's log.  # noqa: E501
        """
        pass

    def test_get_running_jobs(self):
        """Test case for get_running_jobs

        """
        pass

    def test_update_job(self):
        """Test case for update_job

        Updates a Job detail. Returns the updated Job detail.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
