"""
    Katalon TestOps API reference

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import testops_api
from testops_api.api.project_configuration_resource_controller_api import ProjectConfigurationResourceControllerApi  # noqa: E501


class TestProjectConfigurationResourceControllerApi(unittest.TestCase):
    """ProjectConfigurationResourceControllerApi unit test stubs"""

    def setUp(self):
        self.api = ProjectConfigurationResourceControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get14(self):
        """Test case for get14

        """
        pass

    def test_list_time_zones(self):
        """Test case for list_time_zones

        """
        pass

    def test_update10(self):
        """Test case for update10

        """
        pass


if __name__ == '__main__':
    unittest.main()
