# coding: utf-8

"""
    XTRF Home Portal API

    XTRF Home Portal API enables you to perform operations on Projects, Quotes, Customers, Vendors etc. as a XTRF Home Portal user. <br>The documentation is generated from OpenAPI specification 3.0 available <a href=\"/home-api/openapi.json\">here</a> <br>   The API client/consumer code may be easily generated in 60+ programming languages using an open source code generator available at the time of writing this documentation at <a href='https://editor.swagger.io/'>https://editor.swagger.io/</a> Thank you for using XTRF Application Programming interface (XTRF API). By using the API you agree to the terms below. If you disagree with any of these terms, XTRF does not grant you a license to use the XTRF API. XTRF reserves the right to update and change these terms from time to time without a prior notice of API users. You can always find the most recent version of these terms here:   # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.quotes__smart_v2_api import QuotesSmartV2Api  # noqa: E501
from swagger_client.rest import ApiException


class TestQuotesSmartV2Api(unittest.TestCase):
    """QuotesSmartV2Api unit test stubs"""

    def setUp(self):
        self.api = api.quotes__smart_v2_api.QuotesSmartV2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_files2(self):
        """Test case for add_files2

        Adds files to the quote as added by PM.  # noqa: E501
        """
        pass

    def test_archive1(self):
        """Test case for archive1

        Prepares a ZIP archive that contains the specified files.  # noqa: E501
        """
        pass

    def test_change_status2(self):
        """Test case for change_status2

        Changes quote status if possible (400 Bad Request is returned otherwise).  # noqa: E501
        """
        pass

    def test_create3(self):
        """Test case for create3

        Creates a new Smart Quote.  # noqa: E501
        """
        pass

    def test_create_payable1(self):
        """Test case for create_payable1

        Adds a payable to a quote.  # noqa: E501
        """
        pass

    def test_create_receivable1(self):
        """Test case for create_receivable1

        Adds a receivable to a quote.  # noqa: E501
        """
        pass

    def test_delete_payable(self):
        """Test case for delete_payable

        Deletes a payable.  # noqa: E501
        """
        pass

    def test_delete_receivable(self):
        """Test case for delete_receivable

        Deletes a receivable.  # noqa: E501
        """
        pass

    def test_get_by_id10(self):
        """Test case for get_by_id10

        Returns quote details.  # noqa: E501
        """
        pass

    def test_get_contacts3(self):
        """Test case for get_contacts3

        Returns Client Contacts information for a quote.  # noqa: E501
        """
        pass

    def test_get_custom_fields9(self):
        """Test case for get_custom_fields9

        Returns a list of custom field keys and values for a project.  # noqa: E501
        """
        pass

    def test_get_file_by_id2(self):
        """Test case for get_file_by_id2

        Returns details of a file.  # noqa: E501
        """
        pass

    def test_get_file_content_by_id1(self):
        """Test case for get_file_content_by_id1

        Downloads a file content.  # noqa: E501
        """
        pass

    def test_get_files1(self):
        """Test case for get_files1

        Returns list of files in a quote.  # noqa: E501
        """
        pass

    def test_get_finance3(self):
        """Test case for get_finance3

        Returns finance information for a quote.  # noqa: E501
        """
        pass

    def test_get_jobs1(self):
        """Test case for get_jobs1

        Returns list of jobs in a quote.  # noqa: E501
        """
        pass

    def test_update_business_days(self):
        """Test case for update_business_days

        Updates Business Days for a quote.  # noqa: E501
        """
        pass

    def test_update_client_notes1(self):
        """Test case for update_client_notes1

        Updates Client Notes for a quote.  # noqa: E501
        """
        pass

    def test_update_client_reference_number1(self):
        """Test case for update_client_reference_number1

        Updates Client Reference Number for a quote.  # noqa: E501
        """
        pass

    def test_update_contacts(self):
        """Test case for update_contacts

        Updates Client Contacts for a quote.  # noqa: E501
        """
        pass

    def test_update_custom_field1(self):
        """Test case for update_custom_field1

        Updates a custom field with a specified key in a quote.  # noqa: E501
        """
        pass

    def test_update_expected_delivery_date(self):
        """Test case for update_expected_delivery_date

        Updates Expected Delivery Date for a quote.  # noqa: E501
        """
        pass

    def test_update_internal_notes1(self):
        """Test case for update_internal_notes1

        Updates Internal Notes for a quote.  # noqa: E501
        """
        pass

    def test_update_payable1(self):
        """Test case for update_payable1

        Updates a payable.  # noqa: E501
        """
        pass

    def test_update_quote_expiry(self):
        """Test case for update_quote_expiry

        Updates Quote Expiry Date for a quote.  # noqa: E501
        """
        pass

    def test_update_receivable1(self):
        """Test case for update_receivable1

        Updates a receivable.  # noqa: E501
        """
        pass

    def test_update_source_language1(self):
        """Test case for update_source_language1

        Updates source language for a quote.  # noqa: E501
        """
        pass

    def test_update_specialization1(self):
        """Test case for update_specialization1

        Updates specialization for a quote.  # noqa: E501
        """
        pass

    def test_update_target_languages1(self):
        """Test case for update_target_languages1

        Updates target languages for a quote.  # noqa: E501
        """
        pass

    def test_update_vendor_instructions1(self):
        """Test case for update_vendor_instructions1

        Updates instructions for all vendors performing the jobs in a quote.  # noqa: E501
        """
        pass

    def test_update_volume1(self):
        """Test case for update_volume1

        Updates volume for a quote.  # noqa: E501
        """
        pass

    def test_upload_file3(self):
        """Test case for upload_file3

        Uploads file to the quote as a file uploaded by PM.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
