
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-27T14:48:09+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7948a1b238da6c4dbc21445ad6607e76f329d97",
 "version": "2.0.55.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
