# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class LocationSettingsChild(Model):
    """LocationSettingsChild.

    :param max_transport_interval:
    :type max_transport_interval: int
    :param max_vibration_update_interval:
    :type max_vibration_update_interval: int
    :param max_oil_quality_update_interval:
    :type max_oil_quality_update_interval: int
    :param opc_enabled:
    :type opc_enabled: bool
    :param assign_filters_to_account:
    :type assign_filters_to_account: bool
    :param external_notification_type: Possible values include: 'Disabled',
     'Automatic', 'Manual'
    :type external_notification_type: str or ~smartdiagnostics_sdk.models.enum
    """

    _attribute_map = {
        'max_transport_interval': {'key': 'MaxTransportInterval', 'type': 'int'},
        'max_vibration_update_interval': {'key': 'MaxVibrationUpdateInterval', 'type': 'int'},
        'max_oil_quality_update_interval': {'key': 'MaxOilQualityUpdateInterval', 'type': 'int'},
        'opc_enabled': {'key': 'OpcEnabled', 'type': 'bool'},
        'assign_filters_to_account': {'key': 'AssignFiltersToAccount', 'type': 'bool'},
        'external_notification_type': {'key': 'ExternalNotificationType', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(LocationSettingsChild, self).__init__(**kwargs)
        self.max_transport_interval = kwargs.get('max_transport_interval', None)
        self.max_vibration_update_interval = kwargs.get('max_vibration_update_interval', None)
        self.max_oil_quality_update_interval = kwargs.get('max_oil_quality_update_interval', None)
        self.opc_enabled = kwargs.get('opc_enabled', None)
        self.assign_filters_to_account = kwargs.get('assign_filters_to_account', None)
        self.external_notification_type = kwargs.get('external_notification_type', None)
